OBJ := hashTableSearch.o hashTableDelete.o delete_element.o hashTableDestroy.o hashTableInsert.o hashTableCreate.o print_hashTable.o hash_function.o main.o 

main.exe: $(OBJ)
	gcc -o $@ $^

$(OBJ):

clean:
	rm *.o *.exe

