OBJ := insert_before.o insert_after.o delete_element.o delete_list.o delete_last.o delete_first.o insert_at_first.o insert_at_last.o print_list.o main.o

main.exe: $(OBJ)
	gcc -o $@ $^

$(OBJ):

clean:
	rm *.o *.exe
	
