OBJ := reverse.o findLength.o split_alternatively.o countKey.o find_mid.o append.o splithalf.o remove_duplicate.o merge_sortedlinks.o insert_sort.o sorted_insert.o insert_Nth.o getNth.o insert_before.o insert_after.o delete_list.o delete_element.o delete_last.o delete_first.o insert_at_first.o insert_at_last.o main.o print_list.o

main.exe: $(OBJ)
	gcc -o $@ $^

$(OBJ):

clean:
	rm *.o *.exe




