OBJ := create_BST.o delete_BST.o findMin_index_BST.o search_BST.o inorder_Traverse.o preorder_Traverse.o postorder_Traverse.o getTotalNodes.o getTreeHeight.o findMin_BST.o findMax_BST.o main.o 

main.exe: $(OBJ)
	gcc -o $@ $^

$(OBJ):

clean:
	rm *.o *.exe

